Measure-Command{
$pa=@('PLC_A','PLC_B','PLC_C','PLC_D')
$ea=@('Sandextrator overload','Conveyor misalignment','Valve stuck','Temperature warning')
$sa=@('OK','WARN','ERR')

$g=[System.Text.StringBuilder]""
$d=Get-Date
$r=New-Object System.Random

$t=$d.AddSeconds(0).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-1).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-2).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-3).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-4).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-5).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-6).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-7).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-8).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-9).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-10).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-11).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-12).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-13).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-14).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-15).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-16).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-17).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-18).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-19).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-20).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-21).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-22).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-23).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-24).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-25).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-26).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-27).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-28).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-29).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-30).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-31).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-32).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-33).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-34).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-35).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-36).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-37).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-38).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-39).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-40).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-41).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-42).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-43).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-44).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-45).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-46).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-47).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-48).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}
$t=$d.AddSeconds(-49).ToString("yyyy-MM-dd HH:mm:ss");$p=$pa[$r.Next()%4];$o=$r.Next()%20+101;$b=$r.Next()%101+1000;$s=$sa[$r.Next()%3];$m=$r.Next();$l=$r.Next()%101
	if($r.Next()%7){$g.AppendLine("INFO; $t; $p; System running normally; ; $s; $o; $b; $m; $l")}elseif($e=($r.Next()%4)){$e=$ea[$e];$g.AppendLine("ERROR; $t; $p; $e; ; $s; $o; $b; $m; $l")}else{$e=$ea[$e];$v=$r.Next()%10+1;$g.AppendLine("ERROR; $t; $p; $e; $v; $s; $o; $b; $m; $l")}

[System.IO.File]::WriteAllBytes("$PWD\plc_log.txt",[System.Text.Encoding]::UTF8.GetBytes($g))	#Seems faster than Out-File and Set-Content
[System.Console]::WriteLine("PLC log file generated.")	#Faster than Write-Output and Write-Host
}